apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: nexus-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: alerts-volume
              mountPath: /etc/prometheus-alerts/
            - name: storage-volume
              mountPath: /prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: alerts-volume
          configMap:
            name: prometheus-alerts-configmap
        - name: storage-volume
          persistentVolumeClaim:
            claimName: prometheus-storage-pvc
